"""
train.py
--------
Trains the Bengali Morphology Transformer on data/train.tsv, validating on
data/dev.tsv. Saves the best checkpoint (by dev loss) plus the tokenizer
vocabulary to checkpoints/.

Usage:
    python src/train.py --epochs 60 --batch_size 32 --d_model 128

The dataset generated by data/generate_data.py is intentionally small
(a closed rule-derived paradigm set), so this trains in a couple of minutes
on CPU. Point --train_path / --dev_path at a larger corpus (e.g. an
annotated treebank such as IndicNLP / Bengali UD morphology data) to scale
this up without changing any code.
"""

from __future__ import annotations
import argparse
import json
import time
from pathlib import Path

import torch
import torch.nn as nn
from torch.utils.data import DataLoader

from tokenizer import CharTokenizer
from dataset import MorphDataset, build_tokenizer_from_files, collate_batch
from model import BengaliMorphTransformer


def run_epoch(model, loader, optimizer, criterion, device, train: bool):
    model.train() if train else model.eval()
    total_loss, total_tokens = 0.0, 0
    with torch.set_grad_enabled(train):
        for batch in loader:
            src = batch["src"].to(device)
            tgt = batch["tgt"].to(device)
            tgt_in = tgt[:, :-1]
            tgt_out = tgt[:, 1:]

            logits = model(src, tgt_in)
            loss = criterion(logits.reshape(-1, logits.size(-1)), tgt_out.reshape(-1))

            if train:
                optimizer.zero_grad()
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()

            n_tok = (tgt_out != model.pad_id).sum().item()
            total_loss += loss.item() * n_tok
            total_tokens += n_tok
    return total_loss / max(total_tokens, 1)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--data_dir", default="data")
    p.add_argument("--ckpt_dir", default="checkpoints")
    p.add_argument("--epochs", type=int, default=60)
    p.add_argument("--batch_size", type=int, default=32)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--d_model", type=int, default=128)
    p.add_argument("--nhead", type=int, default=4)
    p.add_argument("--enc_layers", type=int, default=3)
    p.add_argument("--dec_layers", type=int, default=3)
    p.add_argument("--dropout", type=float, default=0.1)
    p.add_argument("--seed", type=int, default=13)
    args = p.parse_args()

    torch.manual_seed(args.seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    train_path = str(Path(args.data_dir) / "train.tsv")
    dev_path = str(Path(args.data_dir) / "dev.tsv")

    tokenizer = build_tokenizer_from_files([train_path, dev_path])
    train_ds = MorphDataset(train_path, tokenizer)
    dev_ds = MorphDataset(dev_path, tokenizer)

    pad_id = tokenizer.pad_id
    collate = lambda b: collate_batch(b, pad_id)
    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True, collate_fn=collate)
    dev_loader = DataLoader(dev_ds, batch_size=args.batch_size, shuffle=False, collate_fn=collate)

    model = BengaliMorphTransformer(
        vocab_size=len(tokenizer),
        d_model=args.d_model,
        nhead=args.nhead,
        num_encoder_layers=args.enc_layers,
        num_decoder_layers=args.dec_layers,
        dropout=args.dropout,
        pad_id=pad_id,
    ).to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)
    criterion = nn.CrossEntropyLoss(ignore_index=pad_id)

    ckpt_dir = Path(args.ckpt_dir)
    ckpt_dir.mkdir(exist_ok=True)
    with open(ckpt_dir / "vocab.json", "w", encoding="utf-8") as f:
        json.dump(tokenizer.to_dict(), f, ensure_ascii=False, indent=2)
    with open(ckpt_dir / "config.json", "w") as f:
        json.dump(vars(args), f, indent=2)

    best_dev_loss = float("inf")
    log_path = ckpt_dir / "train_log.txt"
    with open(log_path, "w") as logf:
        for epoch in range(1, args.epochs + 1):
            t0 = time.time()
            train_loss = run_epoch(model, train_loader, optimizer, criterion, device, train=True)
            dev_loss = run_epoch(model, dev_loader, optimizer, criterion, device, train=False)
            dt = time.time() - t0

            line = f"epoch {epoch:3d} | train_loss {train_loss:.4f} | dev_loss {dev_loss:.4f} | {dt:.1f}s"
            print(line)
            logf.write(line + "\n")
            logf.flush()

            if dev_loss < best_dev_loss:
                best_dev_loss = dev_loss
                torch.save(model.state_dict(), ckpt_dir / "best_model.pt")

    print(f"Best dev loss: {best_dev_loss:.4f}. Checkpoint saved to {ckpt_dir / 'best_model.pt'}")


if __name__ == "__main__":
    main()
